/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vighnesh153;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MessageServiceTest {
    @BeforeEach
    void setup() {

    }

    @Test
    void someLibraryMethodReturnsTrue() {
        String message = MessageService.generateMessage();
        assertTrue(message.length() > 0, "should return a non-empty message");
    }
}
