/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 * This project uses @Incubating APIs which are subject to change.
 */

defaultTasks("hello")

tasks.register("hello") {
    println("Hi Shreya")
}

// All available tasks api: org.gradle.api.tasks
tasks.register<Copy>("specialCopy") {
    from("settings.gradle.kts")
    into("$buildDir")
}
